import { test, expect } from "./fixtures";

test.describe("المحتوى المزروع", () => {
  test("القضايا الحيّة والتصويت", async ({ page }) => { await page.goto("/issues"); await expect(page.getByRole("heading", { name: "القضايا الحيّة" })).toBeVisible(); const cards = page.getByRole("article"); await expect(cards.first()).toBeVisible(); expect(await cards.count()).toBeGreaterThan(0); const vote = page.getByRole("button", { name: "هذا يشغلني أيضًا" }).first(); await vote.click(); await expect(page.getByRole("button", { name: "سُجّل اهتمامك" }).first()).toBeVisible(); });
  test("جسر المعرفة القديم يبقى متاحًا للمحتوى المزروع", async ({ page }) => { await page.goto("/knowledge"); await expect(page.getByText("استمرارية صرف الرواتب")).toBeVisible(); await expect(page.getByText("المصدر: تعميم فريق التحول").first()).toBeVisible(); await page.getByRole("link", { name: "لم يتضح" }).click(); await expect(page.getByText("ما صدر توضيح رسمي إلى الآن.").first()).toBeVisible(); await page.getByRole("link", { name: "ما الذي تغيّر" }).click(); await expect(page.getByText("صار الآن")).toBeVisible(); });
  test("الأسئلة تعرض المُجاب وغير المُجاب بحالته", async ({ page }) => { await page.goto("/answers"); await expect(page.getByText("تُحتسب مدة الخدمة السابقة كما هي، ولا يترتب على الانتقال إعادة احتسابها.")).toBeVisible(); const unanswered = page.locator("li").filter({ hasText: "متى تبدأ مرحلة الانتقال الفعلي؟" }).first(); await expect(unanswered).toContainText("ما صدر توضيح رسمي إلى الآن."); });
  test("البحث بلا نتيجة يفتح المشاركة بالنص المكتوب", async ({ page }) => { await page.goto("/answers"); await page.getByLabel("ابحث في الإجابات").fill("موضوع لا وجود له إطلاقًا"); await page.getByRole("button", { name: "اسألنا عنه" }).click(); await expect(page).toHaveURL(/\/ask\?gate=question&t=/); await expect(page.getByLabel("اكتب مشاركتك")).toHaveValue("موضوع لا وجود له إطلاقًا"); });
  test("تأكد من المعلومة يعرض المواقف ويستقبل معلومة جديدة", async ({ page }) => { await page.goto("/rumors"); await expect(page.getByText("«ستتوقف البدلات بعد التحول»")).toBeVisible(); await expect(page.getByText("غير صحيح").first()).toBeVisible(); await expect(page.getByText("«ستُعاد صياغة جميع العقود خلال شهر»")).toBeVisible(); await expect(page.getByText("بانتظار توضيح رسمي").first()).toBeVisible(); await page.getByLabel("اكتب المعلومة اللي سمعتها، وبنساعدك تعرف وش الموقف الرسمي منها.").fill("سمعت أن الدوام سيتغير بعد التحول"); await page.getByRole("button", { name: "أرسل المعلومة" }).click(); await expect(page.getByText("وصلتنا. ما ننشر أي موقف إلا بعد اعتماده رسميًا.")).toBeVisible(); });
  test("رحلة التحول تُظهر المرحلة الحالية", async ({ page }) => { await page.goto("/journey"); const current = page.locator('[aria-current="step"]'); await expect(current).toContainText("الاستعداد"); await expect(current).toContainText("نحن هنا الآن"); });
  test("الاستطلاع يعرض الأسابيع ويقبل ردًا واحدًا", async ({ page }) => { await page.goto("/pulse"); await expect(page.getByRole("heading", { name: "آخر الأسابيع" })).toBeVisible(); await page.getByRole("radio", { name: /إلى حد ما/ }).click(); await page.getByRole("button", { name: "إرسال رأيي" }).click(); await expect(page.getByRole("heading", { name: "وصل رأيك، شكرًا لك" })).toBeVisible(); await expect(page.getByText("لسه عدد الردود قليل، لذلك ما نعرض نتيجة هذا الأسبوع.")).toBeVisible(); });
});
